fix fatal error: decode/descriptor/descriptor.h: No such file or directory
rename libdvbtee/decode/descriptor/descriptor.h to
libdvbtee/decode/descriptor/descript.h to fix an
error when building an app that depends on libdvbtee:
fatal error: decode/descriptor/descriptor.h: No such file or directory

Signed-off-by: Michael Ira Krufky <mkrufky@linuxtv.org>