fix fatal error: dvbtee_config.h: No such file or directory
fix error when building an app that depends on libdvbtee:
fatal error: dvbtee_config.h: No such file or directory

Signed-off-by: Michael Ira Krufky <mkrufky@linuxtv.org>