libdvbtee: fix build breakage due to neither linuxtv nor hdhomerun support being linked in
dvbtee.cpp:(.text.startup+0x67b): undefined reference to `linuxtv_tuner::linuxtv_tuner()'
dvbtee.cpp:(.text.startup+0x6c1): undefined reference to `linuxtv_tuner::set_device_ids(int, int, int, int, bool)'
dvbtee.cpp:(.text.startup+0x75e): undefined reference to `hdhr_tuner::hdhr_tuner()'
dvbtee.cpp:(.text.startup+0xb15): undefined reference to `hdhr_tuner::hdhr_tuner()'
dvbtee.cpp:(.text.startup+0xb3a): undefined reference to `hdhr_tuner::set_hdhr_id(char const*, bool)'
dvbtee.cpp:(.text.startup+0xb59): undefined reference to `linuxtv_tuner::linuxtv_tuner()'

Signed-off-by: Michael Ira Krufky <mkrufky@linuxtv.org>