output: fix build error due to missing include
output.cpp: In constructor ‘output_stream::output_stream()’:
output.cpp:39: error: ‘memset’ was not declared in this scope
output.cpp: In copy constructor ‘output_stream::output_stream(const output_stream&)’:
output.cpp:54: error: ‘memset’ was not declared in this scope
output.cpp: In member function ‘output_stream& output_stream::operator=(const output_stream&)’:
output.cpp:65: error: ‘memset’ was not declared in this scope
output.cpp: In member function ‘int output_stream::add(char*)’:
output.cpp:143: error: ‘strstr’ was not declared in this scope
output.cpp:144: error: ‘strtok’ was not declared in this scope
output.cpp:160: error: ‘memset’ was not declared in this scope
output.cpp: In constructor ‘output::output()’:
output.cpp:190: error: ‘memset’ was not declared in this scope

Signed-off-by: Michael Krufky <mkrufky@linuxtv.org>