configure.ac: remove AC_FUNC_MALLOC & AC_FUNC_STRCOLL
Remove AC_FUNC_MALLOC & AC_FUNC_STRCOLL, since neither these
nor `HAVE_MALLOC` / `HAVE_STRCOLL` are actually being used.

Under certain circumstances, the following error is caused:
```
i686/include/c++/6.1.0/stdlib.h:65:12: error: 'std::malloc' has not been declared
```
In this case, this is a Windows 64 bit cross-build using GCC 6.1 under Linux.

Signed-off-by: Michael Ira Krufky <mkrufky@linuxtv.org>